name: Test

on:
  push: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - run: go version

      - name: Test
        run: |
          go test ./...

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - run: |
          mkdir -p dist

      - name: build
        uses: docker/build-push-action@v6
        with:
          push: false
          file: build.Dockerfile
          outputs: type=local,dest=./dist
          cache-from: type=gha
          cache-to: type=gha

      - run: |
          ls -al dist
